# Generated by Django 3.2.3 on 2021-06-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TTS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tts',
            name='file',
            field=models.FileField(upload_to='tts/'),
        ),
    ]
